name = "leaf"
version = "0.1.0"
description = "A static site/blog/doc generator"
authors = ["NikolasSkyl"]
licences = ["MIT"]
repository = { type = "github", user = "NikolasSkyl", repo = "leaf" }
# links = [{ title = "Website", href = "" }]

[dependencies]
donna = { git = "https://github.com/donna-lang/donna_stdlib", version = ">=0.1.0 and <1.0.0" }
argparse = { git = "https://github.com/donna-lang/argparse", version = ">=0.1.0 and <1.0.0" }
parsetoml = { git = "https://github.com/donna-lang/parsetoml", version = ">=0.1.0 and <1.0.0" }
markdown = { git = "https://github.com/NikolasSkyl/markdown", version = ">=0.1.0 and <1.0.0" }
mustache = { git = "https://github.com/NikolasSkyl/mustache", version = ">=0.1.1 and <1.0.0" }
mongoose = { git = "https://github.com/NikolasSkyl/mongoose", version = ">=0.1.1 and <1.0.0" }

[dev-dependencies]
unittest = { git = "https://github.com/donna-lang/unittest", version = ">=0.1.0 and <1.0.0" }
